### ISSUE TITLE
Le hello.txt a de l'espagnol

### ISSUE THREAD

**Issue by Antoine-bdc** [Rami-Louati/DevopsCourse#1]
Bonjour, ceci est un projet en franglais, veuillez ne pas écrire en espagnol ni polonais. Merci

**Comment by Rami-Louati** [comment]
Bien reçu, on travaille dessus, merci de votre retour.

**Comment by Antoine-bdc** [comment]
Issue resolved. See commit https://github.com/Rami-Louati/DevopsCourse/commit/3487f218cdd666357f8c6b41d2fb80416847f86d
